service: ${file(config.${opt:stage}.json):NAME}

provider:
  name: aws
  runtime: nodejs12.x
  region: ${file(config.${opt:stage}.json):REGION}
  stage: ${file(config.${opt:stage}.json):STAGE}
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}
    APIFY_KEY: ${file(config.${opt:stage}.json):APIFY_KEY}
    CRAWLERS_TABLE: ${cf.${self:provider.region}:${self:service.name}-${self:provider.stage}.CrawlersTable}
  apiGateway:
    binaryMediaTypes:
      - "*/*"

  versionFunctions: false
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
            - "s3:*"
          Resource: "*"

custom:
  defaultStage: ${self:provider.stage}
  currentStage: ${self:provider.stage}

package:
  patterns:
    - node_modules/**

functions:
  - ${file(src/parser/index.yml)}
resources:
  - ${file(resources/ddb_crawler.yml)}
  - Outputs:
      CrawlersTable:
        Value:
          Ref: CrawlersTable
