Resources:
  CrawlersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:provider.stage}-crawler
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
      KeySchema:
        - AttributeName: url
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
